Prac7/proj7/app7/urls.py
from django.urls import path
from . import views

app_name = 'app7'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name="post_detail")
]

Prac7/proj7/proj7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app7/', include('app7.urls', namespace='app7'))
]

# app_name = app ka naam,
# namespace = project ko us app se jodne ka bridge.

Prac7/proj7/app7/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

Prac7/proj7/app7/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def post_list(request):
    posts = Post.objects.order_by('-created_at') # descending order: Fetch all posts, newest first
    return render(request, 'post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)# Fetch post by primary key or show 404
    return render(request, 'post_detail.html', {'post': post})

# render - showing a webpage or template with data

'''
IMPORTANT CONCEPTS

1. ForeignKey vs CharField: Use ForeignKey for relational integrity.
2. auto_now_add vs auto_now: Creation time vs updated time.
3. get_object_or_404: Safer than .get() to avoid 500 errors.
4. Template Tags:
    {{ }} = variable
    {% %} = logic/control
5. URL Namespacing: app_name + name ensures links are dynamic.
6. Admin registration: Without it, model won’t appear in admin.
7. Queryset ordering: .order_by('-created_at') = newest first
'''

Prac7/proj7/app7/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{post.title}}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "style.css" %}">
</head>
<body>
    <h1>{{post.title}}</h1>
    <p>By {{ post.author }} on {{post.created_at}}</p>
    <div>{{post.body}}</div>
    <p><a href="{% url 'app7:post_list' %}">Back</a></p>
</body>
</html>

Prac7/proj7/app7/templates/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "style.css" %}">
</head>
<body>
    <h1>All Posts</h1>
    <ul>
        {% for post in posts %}
            <li>
                <a href="{% url 'app7:post_detail' post.pk %}">
                    {# dynamically generating url #}
                    {# uses namespace (app6) + URL name (post_detail) from urls.py #}
                    {# If you don’t define app_name = 'app6' in your app-level urls.py, Django won’t recognize the namespace #}
                    {{ post.title }}
                </a>
                    -- {{ post.author }} ({{ post.created_at }})
            </li>
        {% empty %}
            <li>No posts yet</li>
        {% endfor %}
    </ul>
</body>
</html>